#有以下配置后，就不需要application.properties文件了【二选一即可】
spring:
  application:
    name: tlias-web-management
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wjp7867137639
  servlet:
    multipart:
      # 最大单个文件大小
      max-file-size: 10MB
      # 最大请求大小(包括所有文件和表单数据)
      max-request-size: 100MB

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 方式三：开启驼峰命名，如果字段名与属性名符合驼峰命名规则，则mybatis会自动通过驼峰命名规则映射。
    map-underscore-to-camel-case: true


#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: daykalif-java-ai2
    region: cn-beijing